export const SET_PROJECT_TITLE = "SET_PROJECT_TITLE"
export const SET_PROJECT_CONTENTS = "SET_PROJECT_CONTENTS"
export const SET_PROJECT_REGION = "SET_PROJECT_REGION"
export const SET_PORJECT_LEVEL = "SET_PROJECT_LEVEL"
export const SET_PROJECT_LONG = "SET_PROJECT_LONG"
export const ADD_PORJECT_POSITION = "ADD_PROJECT_POSITION"
export const RMV_PORJECT_POSITION = "RMV_PROJECT_POSITION"
export const SET_PROJECT_NOWTEAM = "SET_PROJECT_NOWTEAM"
export const ADD_PROJECT_KEYWORD = "ADD_PROJECT_KEYWORD"
export const RMV_PROJECT_KEYWORD = "RMV_PROJECT_KEYWORD"
export const SET_PROJECT_IMAGE = "SET_PROJECT_IMAGE"

export const MOVE_TO_SECONDPAGE = "MOVE_TO_SECONDPAGE"

export const KEYWORD_ON_CLICK = "KEYWORD_ON_CLICK"


/* 질문 관련 액션*/
export const ADD_QUESTION_LIST = "ADD_QUESTION_LIST"
export const RMV_QUESTION_LIST = "RMV_QUESTION_LIST"
export const SET_QUESTION_TEXT = "SET_QUESTION_TEXT"

/* 데이터 전송 액션 */
export const POST_PROJECT_REQUEST = "POST_PROJECT_REQUEST"
export const POST_PROJECT_SUCCESS = "POST_PROJECT_SUCCESS"
export const POST_PROJECT_FAILURE = "POST_PROJECT_FAILURE"


/* change 시 기존데이터 요청 */
export const GET_PROJECT_REQUEST = "GET_PROJECT_REQUEST"
export const GET_PROJECT_SUCCESS = "GET_PROJECT_SUCCESS"
export const GET_PROJECT_FAILURE = "GET_PROJECT_FAILURE"

/* 포스트 수정 요청*/
export const PATCH_PROJECT_REQUEST = "PATCH_PROJECT_REQUEST"
export const PATCH_PROJECT_SUCCESS = "PATCH_PROJECT_SUCCESS"
export const PATCH_PROJECT_FAILURE = "PATCH_PROJECT_FAILURE"