/* 리덕스의 패턴에서 action에 들어가는 파일들을 작성하는 장소입니다. */

export const ADD_SELECTORS_CONTENT = "ADD_SELECTORS_CONTENT"
export const REMOVE_SELECTORS_CONTENT = "REMOVE_SELECTORS_CONTENT"
export const SET_SELECTED_PAGES = "SET_SELECTED_PAGES"

export const CLEAR_SELECTED_KYEWORD = "CLEAR_SELECTED_KYEWORD"

export const NEXT_APPLY_MODAL = "NEXT_APPLY_MODAL"
export const PREV_APPLY_MODAL = "PREV_APPLY_MODAL"
