/* 리덕스의 패턴에서 action에 들어가는 파일들을 작성하는 장소입니다. */

export const ADD_SELECTORS_CONTENT = "ADD_SELECTORS_CONTENT"
export const REMOVE_SELECTORS_CONTENT = "REMOVE_SELECTORS_CONTENT"
export const SET_SELECTED_PAGES = "SET_SELECTED_PAGES"

export const CLEAR_SELECTED_KYEWORD = "CLEAR_SELECTED_KYEWORD"

export const NEXT_APPLY_MODAL = "NEXT_APPLY_MODAL"
export const PREV_APPLY_MODAL = "PREV_APPLY_MODAL"
export const OPEN_APPLY_MODAL = "OPEN_APPLY_MODAL"
export const CLOSE_APPLY_MODAL = "CLOSE_APPLY_MODAL"

export const SET_APPLYQNA_DATA = "SET_APPLYQNA_DATA"

export const GET_MYDATA_REQUEST = "GET_MYDATA_REQUEST"
export const GET_MYDATA_SUCCESS = "GET_MYDATA_SUCCESS"
export const GET_MYDATA_FAILURE = "GET_MYDATA_FAILURE"

export const ADD_PORTFOLIO_MODAL = "ADD_PORTFOLIO_MODAL"
export const DEL_PORTFOLIO_MODAL = "DEL_PORTFOLIO_MODAL"