/* 리덕스의 패턴에서 action에 들어가는 파일들을 작성하는 장소입니다. */

export const ADD_SELECTORS_CONTENT = "ADD_SELECTORS_CONTENT";
export const REMOVE_SELECTORS_CONTENT = "REMOVE_SELECTORS_CONTENT";
export const SET_SELECTED_PAGES = "SET_SELECTED_PAGES";

export const CLEAR_SELECTED_KYEWORD = "CLEAR_SELECTED_KYEWORD";

export const NEXT_APPLY_MODAL = "NEXT_APPLY_MODAL";
export const PREV_APPLY_MODAL = "PREV_APPLY_MODAL";
export const OPEN_APPLY_MODAL = "OPEN_APPLY_MODAL";
export const CLOSE_APPLY_MODAL = "CLOSE_APPLY_MODAL";

export const SET_APPLYQNA_DATA = "SET_APPLYQNA_DATA";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE";
export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAILURE = "USER_LOGOUT_FAILURE";

export const GET_MYDATA_REQUEST = "GET_MYDATA_REQUEST";
export const GET_MYDATA_SUCCESS = "GET_MYDATA_SUCCESS";
export const GET_MYDATA_FAILURE = "GET_MYDATA_FAILURE";

export const ADD_PORTFOLIO_MODAL = "ADD_PORTFOLIO_MODAL";
export const DEL_PORTFOLIO_MODAL = "DEL_PORTFOLIO_MODAL";

export const ADD_KEYWORD_LIST = "ADD_KEYWORD_LIST";
export const DEL_KEYWORD_LIST = "DEL_KEYWORD_LIST";
export const DEL_KEYWORDS_ALL = "DEL_KEYWORDS_ALL";

export const OPEN_LOGIN_MODAL = "OPEN_LOGIN_MODAL";
export const CLOSE_LOGIN_MODAL = "CLOSE_LOGIN_MODAL";

export const SET_LOGIN_MODAL = "SET_LOGIN_MODAL";

export const SET_KEYWORDS_REQUEST = "SET_KEYWORDS_REQUEST";
export const SET_KEYWORDS_SUCCESS = "SET_KEYWORDS_SUCCESS";
export const SET_KEYWORDS_FAILURE = "SET_KEYWORDS_FAILURE";

export const GET_KEYWORDS_REQUEST = "GET_KEYWORDS_REQUEST";
export const GET_KEYWORDS_SUCCESS = "GET_KEYWORDS_SUCCESS";
export const GET_KEYWORDS_FAILURE = "GET_KEYWORDS_FAILURE";

export const REPAIR_PASSWORD = "REPAIR_PASSWORD";

export const USER_JOIN_REQUEST = "USER_JOIN_REQUEST"
export const USER_JOIN_SUCCESS = "USER_JOIN_SUCCESS"
export const USER_JOIN_FAILURE = "USER_JOIN_FAILURE"

export const ADD_JOB_VALUE = "ADD_JOB_VALUE"
export const SUB_JOB_VALUE = "SUB_JOB_VALUE"

export const GET_MYPORTFOLIO_REQUEST = "GET_MYPORTFOLIO_REQUEST"
export const GET_MYPORTFOLIO_SUCCESS = "GET_MYPORTFOLIO_SUCCESS"
export const GET_MYPORTFOLIO_FAILURE = "GET_MYPORTFOLIO_FAILURE"
export const PROJECT_ENROLLMENT_REQUEST = "PROJECT_ENROLLMENT_REQUEST";
export const PROJECT_ENROLLMENT_SUCCESS = "PROJECT_ENROLLMENT_SUCCESS";
export const PROJECT_ENROLLMENT_FAILURE = "PROJECT_ENROLLMENT_FAILURE";

export const PROJECT_APPLY_REQUEST = "PROJECT_APPLY_REQUEST";
export const PROJECT_APPLY_SUCCESS = "PROJECT_APPLY_SUCCESS";
export const PROJECT_APPLY_FAILURE = "PROJECT_APPLY_FAILURE";

export const GET_QUESTION_REQUEST = "GET_QUESTION_REQUEST";

export const GET_FAVORITE_REQUEST = "GET_FAVORITE_REQUEST";
export const GET_FAVORITE_SUCCESS = "GET_FAVORITE_SUCCESS";
export const GET_FAVORITE_FAILURE = "GET_FAVORITE_FAILURE";
export const GET_FAVORITE_FLUSH = "GET_FAVORITE_FLUSH";

export const ADD_FAVORITE_REQUEST = "ADD_FAVORITE_REQUEST";
export const ADD_FAVORITE_SUCCESS = "ADD_FAVORITE_SUCCESS";
export const ADD_FAVORITE_FAILURE = "ADD_FAVORITE_FAILURE";

export const DELETE_FAVORITE_REQUEST = "DELETE_FAVORITE_REQUEST";
export const DELETE_FAVORITE_SUCCESS = "DELETE_FAVORITE_SUCCESS";
export const DELETE_FAVORITE_FAILURE = "DELETE_FAVORITE_FAILURE";
